# Generated by Django 3.0.6 on 2020-05-08 09:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0002_remove_album_year'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='song',
            name='title',
        ),
    ]
